import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["noorcast.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        SpeechSynthesisUtterance: "readonly",
        speechSynthesis: "readonly",
        FaceDetector: "readonly",
        FormData: "readonly",
        URLSearchParams: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        fetch: "readonly",
        URL: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        Audio: "readonly",
        HTMLCanvasElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLElement: "readonly",
        Event: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        DragEvent: "readonly",
        ClipboardEvent: "readonly",
        MediaRecorder: "readonly",
        MediaStream: "readonly",
        AudioContext: "readonly",
        OfflineAudioContext: "readonly",
        GainNode: "readonly",
        BlobEvent: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        performance: "readonly",
        Intl: "readonly",
        self: "readonly",
        showDirectoryPicker: "readonly",
        SpeechRecognition: "readonly",
        webkitSpeechRecognition: "readonly",
        ResizeObserver: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        CanvasRenderingContext2D: "readonly",
        OffscreenCanvas: "readonly",
        createImageBitmap: "readonly",
        queueMicrotask: "readonly",
        structuredClone: "readonly",
        crypto: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        AbortController: "readonly",
        WritableStream: "readonly",
        showSaveFilePicker: "readonly",
        MediaMetadata: "readonly",
        getComputedStyle: "readonly",
        ClipboardItem: "readonly",
      },
    },
    rules: {
      // Relax rules for this single-file app pattern
      "no-unused-vars": ["warn", {
        varsIgnorePattern: "^(APP_VERSION|BUILD_DATE|LANG|Engine|Recorder|Scenes|Templates|Laser|Freeze|Whiteboard|Teleprompter|Snapshot|Sensors|SoundBoard|Badges|Confetti|Ticker|Chapters|History|LayoutHistory|Zoom|Drag|Grid|SourceLabels|FpsCounter|Brand|Watermark|ServoGauge|SensorOverlay|Spotlight|CursorTrail|FocusMode|Tour|Clock|RecIndicator|AudioViz|RecElapsed|Letterbox|Vignette|SceneTimer|Timelapse|TimeGoal|Captions|MicMeter|MicCheck|MicrobitOverlay|SourceSkins|BgPatterns|InstantReplay|VoiceCommands|DailyChallenges|AutoThumbnail|PostTranscript|SmartSceneSwitcher|TutorialScore|AICohost|LessonGuide|RobotChoreo|MultiTakeDirector|QRShare|VisualCrop|CanvasFlair|UnlockGallery|ComboSystem|GhostReplay|CanvasPets|ExportFlyer|GlobalSearch|SceneThemes|VoiceFx|SpeedLines|XpBar|AchievementPopup|SoundPad|BgMusic|StickyNotes|Duck|SceneSaver|ScreenSaver|SceneIntro|AutoAdvance|Jingle|IntroOutro|Sfx|DebugHud|DailyTip|OnboardWizard|KeyBinds|LogoGallery|BrandPresets|SnapGrid|SettingsBundle|TextOverlay|SourceStylePopup|$|t|applyI18n|showToast|log|SensorGraph|safe|EventBus|debounce|silentGet|silentSet|silentSetJSON|silentGetJSON|silentRemove|SafeZone|StageStatus|WorkflowSteps|KidsMode|WhatsNew|Tour|AutoFrame|AutoChapters|ReelsTrim|RecordQuality|StageAspect|AICohost|SnapshotAnnotator|VolumeDuck|MicBoost|LiveCaptions|InstantReplay|SilenceTrim|UiFont|CustomAccent|CanvasBg|GhostReplay|SourcePulse|TextStamps|SceneTransition|ClockOverlay|CountdownTimer|RecIndicator|AudioViz|Reactions|SidebarResize|SettingsState|SceneAutoSave|MicrobitOverlay|Drag|Brand|GridOverlay|Trim|FACE_DETECTOR|ChapterList|Waveform|BadgeCard|SensorTimeline|SensorChart|TextStamps)",
        argsIgnorePattern: "^(_|W$|H$|ctx$|ev$|e$|t$|i$|pet$|frozen$)",
        caughtErrorsIgnorePattern: "^(_|e|err|ex)$",
      }],
      "no-redeclare": "error",
      "no-undef": "error",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-prototype-builtins": "off",
      "no-fallthrough": "warn",
      "no-case-declarations": "warn",
      "no-useless-escape": "warn",
      "no-inner-declarations": "off",
    },
  },
  {
    ignores: ["sw.js", "node_modules/", "tests/", "etsy-package/NoorCast-v*/"],
  },
];
